version: "3.9"
 
services:

  django:
    build: .
    command: bash -c "daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"

  redis:
    container_name: redis
    image: redis:latest
    restart: always